name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=vendor
      GOPROXY: "off"

    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
